title: Rundong Zhao
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Rundong Zhao # add your name
author-img: avatar.jpg # add your photo
about-author: I'm a geometer who is honorable to work closely with Albert Einstein. I'm very interested in the geometric anatomy of theoretical physics. Except that, I loving travelling and hiking. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: rdzhao # add your Github handle
social-linkedin: rundong-zhao-1080a7b1 # add your Linkedin handle
social-email: zhaorund@msu.edu # add your Email address

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 20
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
